application: glcacs-1048
version: 1
runtime: python27
api_version: 1
threadsafe: true


# [START handlers]
handlers:

- url: /files
  static_dir: files

- url: /images
  static_dir: images

- url: /.*
  script: glcacs.app
# [END handlers]


# [START libraries]
libraries:
- name: webapp2
  version: 2.5.1
# [END libraries]



